"""Adds repositories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/bazel-rules-backward-cpp repository. If 
# you encounter it anywhere else it is because it has been copied
# there in order to simplify adding transitive dependencies. If you
# want a different version of bazel-rules-tclap follow the Bazel build
# instructions at https://github.com/3rdparty/bazel-rules-backward-cpp.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def repos(external = True, repo_mapping = {}):
    if external:
        maybe(
            git_repository,
            name = "com_github_3rdparty_backward_cpp",
            remote = "https://github.com/ArthurBandaryk/bazel-backward-cpp",
            commit = "971a376dc754faeb4fe47468fc52a7022c73448d",
            shallow_since = "1653393117 +0300",
            repo_mapping = repo_mapping,
        )
